specVersion: 0.2.0
name: xc20-data
version: 1.0.0
description: >-
  A basic Frontier EVM example project with an event and call handler. Read more
  about this at https://doc.subquery.network/create/frontier/. This project can
  be use as a starting point for developing your SubQuery project
repository: 'https://github.com/subquery/tutorials-frontier-evm-starter'
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xfe58ea77779b7abda7da4ec526d14db9b1e9cd40a217c34892af80a9b332b76d'
  endpoint: 'wss://moonbeam.api.onfinality.io/public-ws'
  dictionary: 'https://api.subquery.network/sq/subquery/moonbeam-dictionary'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 950000
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: assets
            method: Transferred
